### ISSUE TITLE
[s3] rank at battles page

### ISSUE THREAD

**Issue by paul-sama** [fetus-hina/stat.ink#1094]
battles page, `Rank` and `Rank (After)` not show for `Anarchy Battle (Series)`

**Comment by Toufool** [comment]
Also having this same issue, I can provide a few examples. Here is my Splat Log: https://stat.ink/@Toufool/spl3

`Rank` and `Series Progress` used to show on the battle page, for example this battle: https://stat.ink/@Toufool/spl3/dba94856-8c7f-4d73-bc50-d96842ce1358

This recent battle does not have those stats https://stat.ink/@Toufool/spl3/42dd652c-0ff7-4aff-8898-0efd157f2835

This may be already known because I know that support is still on going for splatoon 3, but thought I would point it out just in case

**Comment by fetus-hina** [comment]
Maybe s3s side.
@frozenpandaman

**Comment by frozenpandaman** [comment]
Yep, seems like an error on s3s's end, if I had to guess… 

See discussion at the issue @paul-sama referenced above.

**Comment by frozenpandaman** [comment]
@Toufool Currently `Series Progress` is only sent for the last battle in a series or at the end of a rotation – per (to my understanding, but I may be missing some info…) how they're displayed in the Anarchy overview screen in SplatNet 3.
