### ISSUE TITLE
"number" in player structure might not always be integer

### ISSUE THREAD

**Issue by k-ashiya** [fetus-hina/stat.ink#1099]
I've uploaded some battle results via s3s, and caught the message below:

> {"error": {"their_team_players": "number: Number must be an integer."}}

In this "malformed" data, one of the players has the following profile:

>"nameId":"","name":"Player","byname":"バンカラな若者"

The field is blank probably because they're on the first battle.

I've also encountered an player whose "nameId" includes an alphabet (although this is much rare and seems buggy...) so I think that "number" in player structure shouldn't be required to be integer.

**Comment by fetus-hina** [comment]
Thank you for the report.

I tested in a dev env and confirmed that `"#id"` is handled correctly if it is an empty string, if it consists of only spaces, or if the parameter does not exist.
(The error you point out occurs if you give something that is not a number, such as `abc`.)

開発環境で確認したところ、 `#id` 部分が空文字列の場合や(半角)スペースで構成されている場合、または、パラメータが存在しない場合には正常に動作するようです。（アルファベットなどを与えた場合はご指摘のエラーになります）

Also, the code in the s3s conversion section seems to take into account the case where nameId is not present, and since it is not specifically processed, an empty string seems to work.

また、s3sの変換部分のコードを見る限りは nameId が存在しない場合についても考慮されており、また、特に加工はしていないので空文字列は動作するように思えます。

https://github.com/frozenpandaman/s3s/blob/1e0bc147d7229d6d656cfce46d54c00026e7579d/s3s.py#L371-L374

@k-ashiya If you can, would you please share the JSON file with us?
もし可能でしたら、当該 JSON ファイルを共有していただけませんか？

@frozenpandaman Do you have any opinions on these?

**Comment by k-ashiya** [comment]
Ah... sorry for my misunderstanding.
Blank "nameId" seems correctly treated because my first battle result (all players are "Player") has been uploaded successfully.

Now the issue is that "nameId" might include alphabets.
Here's the JSON which one of the players has an alphabet in their "nameId", extracted from s3s exports.
[battle_20220914154658.txt](https://github.com/fetus-hina/stat.ink/files/9684085/battle_20220914154658.txt)

**Comment by fetus-hina** [comment]
I have created and deployed a workaround for this issue.
If non integer-like values are given, including alphabetic characters, the number will not be recorded. (like first play "Player")
The workaround causes the player to not see `#1234`, but I think that is a minor display issue.

**Comment by frozenpandaman** [comment]
If the value is a blank string, s3s sends `None` (null), and otherwise sends the number. If there are alphabetic characters, s3s will still send the string so it is up to stat.ink to accept it.

.I've also encountered an player whose "nameId" includes an alphabet (although this is much rare and seems buggy...) 

?!? Do you have a picture, though? omg

**Comment by fetus-hina** [comment]
Another user reported same issue with a screenshot and a replay data (it called "バトルメモリー"[Battle Memory] in Japanese).
I updated the code to accept latin alphabet.
Just to let you know for the record.
