### ISSUE TITLE
The drop down menu of "Language" seems not be affected in all translation

### ISSUE THREAD

**Issue by ADeeeee** [fetus-hina/stat.ink#1109]
Issue:
For example in Japanese
![image](https://user-images.githubusercontent.com/35981633/193461389-70c5b2a1-ce2e-4875-80ec-805159c5b75b.png)

Expect: 
Showing "言語"

Detail:
Shouldn't it be affected by this variable (https://github.com/fetus-hina/stat.ink/blob/dev/messages/ja/app.php#L276)? It always shows Language no matter you use any translation so far. I'm not sure if it's correct by design.

By the way, there seems no variable for "Wash your hands to stay fresh!".

**Comment by fetus-hina** [comment]
No. By design. It is a common mistake to translate an application's language switch.
When a persona who only understands English accidentally switches to Chinese, it is difficult to switch back to English.
I believe that the display of icons and English language is useful as a maximum common denominator.

> Detail

Its translation catalog is used for the Slack notification language within the setting.

> By the way, there seems no variable for "Wash your hands to stay fresh!".

At this time, there is no way to translate that message.
Since COVID seems to be settling down, I may remove the banner soon.
