### ISSUE TITLE
`/api/v3/ability` returns unofficial translations

### ISSUE THREAD

**Issue by spacemeowx2** [fetus-hina/stat.ink#1127]
With the addition of the reporting field for gear in stat.ink, s3si.ts was the first to implement the reporting of gear.

Since the `ability` returned from the official API only has `name`, a `name` -> `key` mapping is needed.

I thought that the api `/api/v3/ability?full=1` mentioned in the `info` of the `primary_ability` field would have the same name as the official one, but it doesn't.

For example, in `zh-CN`, `sub_power_up` is officially shown as `提升次要武器性能`, while the API in stat.ink shows `副武器增强`.

Fortunately, there is an official API that lists all `ability`(myOutfitCommonDataFilteringConditionQuery). I wrote a script to get the names of all `ability`: https://github.com/spacemeowx2/s3si.ts/blob/main/scripts/generate-gear-map.ts

And here is the result: https://gist.github.com/spacemeowx2/56377320c219c30139887ec71d9687e6

I think it would be better if `/api/v3/ability?full=1` returned the official name。

**Comment by spacemeowx2** [comment]
It does not only happen in `zh-CN`, but also in `ja-JP`. 

For example, `インク効率アップ（メイン）` (stat.ink) -> `インク効率アップ(メイン)` (official). The characters in brackets are not the same

**Comment by fetus-hina** [comment]
The localized-names returned by the API are intended for display to the user and are not suitable for exact matching.
This is because most of them are copies of the content of the Inkipedia pages, so we cannot guarantee the content.
The Japanese full-width and half-width are trivial and simply due to my input, but the case of Simplified Chinese is due to past contributions.
(They are derived from the "slang" for Splatoon 2 and should be updated to the latest as well as Traditional Chinese)They are in the controllable zone, but I don't think `es-MX` and `fr-CA` in particular are trustworthy.
`es-MX` and `fr-CA` probably do not have enough editors for Inkipedia.

**Comment by fetus-hina** [comment]
All translations regarding abilities have been updated with [the data provided by Splatoon3.ink](https://github.com/misenhower/splatoon3.ink/wiki/Data-Access#locales).
I think the issue has improved a bit, but I don't know if everything is resolved.

**Comment by spacemeowx2** [comment]
Thanks for the fix! I'll make some minor changes and upload a few games to test using `stat.ink`'s API.
