### ISSUE TITLE
Saving Side Order run results and stats

### ISSUE THREAD

**Issue by g3335491** [fetus-hina/stat.ink#1262]
SplatNet 3 provides data for Side Order runs. Will you consider also tracking them on stat.ink?

**Comment by fetus-hina** [comment]
Our scope is stats for "multi-player mode."
At this point in time, when I am playing the second run, I have not found any specific factors to record/manage, and I don't think I will implement something.

- What I might implement:
  - Online battle mode (Regular, Anarchy, Challenge, Splatfest, Private)
  - Online Coop mode (Salmon Run, Big Run, Eggstra Work)
  - Online mini-game (Online Tableturf)
- What I will NOT implement:
  - Offline battle mode (The Shoal, Battle Dojo)
  - Offline single-player mode (Story Mode: Octo Valley, Return of the Mammalians, Octo Expansion, **Side Order**, Offline Tableturf battle)

Note: As for Tableturf, I have not actually implemented anything, but it is a possibility.

BTW, I already implemented the 11 weapons that you get as rewards after run the Side Order, because they appear in the multiplayer mode.
