### ISSUE TITLE
[Help] Battles reported twice

### ISSUE THREAD

**Issue by Wolfy76700** [fetus-hina/stat.ink#361]
Hi there! I just wanted to mention that, on [my Stat.ink profile](https://stat.ink/@MathiasWolfbrok/spl2?filter%5Brule%5D=standard-regular-nawabari), some battles are listed twice due to me having to reupload the new Splatfest data thanks to the newest version of Splatnet2statink. Indeed, I think the first upload may have incomplete data due to being uploaded via Splatstats.

Does anyone know how to batch fix the results please?

**Comment by frozenpandaman** [comment]
@Wolfy76700 Sorry about that. 😅 I tried to get the new update out ASAP after Splatfest started (while I myself was playing too) so people could hopefully start uploading correct & complete data (for the new Splatfest system!) before any older battles (>50) got overwritten on SplatNet. @fetus-hina was also a big help in really quickly changing it so EXP could go up to 999 instead of just 99, meaning battles (even if incomplete) could actually upload instead of getting an error message in response.

Anyway, your question: I know there was a [v1 API endpoint](https://github.com/fetus-hina/stat.ink/blob/master/doc/api-1/delete-battle.md) for deleting battles (`/api/v1/battle`, Method `DELETE`) which you could automate with a script. But it looks like you only have 5 duplicate battles, so that shouldn't be hard to do by hand. When I need to delete multiple, I just Ctrl+click "Detail" to open 'em all in a new tab, then switch between the tabs (keyboard shortcuts are helpful for this!) clicking Edit on each one, then scroll down on all the pages, and then go through one last time and check the box & click Delete.

**Comment by frozenpandaman** [comment]
Oooh, I see. Yeah, I've found it doesn't take *that* long by hand, but it definitely could be easier. 😬 (But of course you don't want people to abuse the feature either, as noted above the deletion confirmation checkboxes…) splatnet2statink has a feature that prevents duplicates from being uploaded based on battle UUID – did you have to delete the ones by hand before you could upload the new ones with the new version? (If so, we might be able to add a [custom key](https://github.com/frozenpandaman/splatnet2statink/wiki/custom-keys) that allows you to upload duplicates if you need for some reason…)

By Splatstats you mean that [Twitter account](https://twitter.com/splatstats) that posts reports about the state of different competitive teams? Sorry, that's all I really know about it.

**Comment by Wolfy76700** [comment]
Oh, sorry, I meant Squidtracks ^^ I  have a bad habit of mixing both up

But no, basically Splatnet2statink didn't check for duplicates and just re-uploaded the current contents of Splatnet, maybe due to the old contents being uploaded from a different client

**Comment by frozenpandaman** [comment]
Oh, yeah, it'll reupload anything you already have there as uploaded by SquidTracks – we set a UUID, as defined by @fetus-hina here: https://github.com/frozenpandaman/splatnet2statink/issues/30#issuecomment-358946890 But I don't think SquidTracks does this.

If you try to reupload those same battles you already just uploaded with splatnet2statink, you'll get a message saying they're already uploaded/duplicates. So s2s *did* check for duplicates, but just didn't find anything – because SquidTracks didn't set any old UUID to check against, most likely. We *could* check by SplatNet battle # in addition, but also I don't really see people switching between clients too often (you just use one or the other) – and if you do switch or use another one (e.g. because s2s provides more info than ST) you'll probably *want* to reupload them anyway (or, have the option to before having to deleting the old records one by one, by hand) to get the full amount of data for as many battles as you can.
