### ISSUE TITLE
Icon column show weapons

### ISSUE THREAD

**Issue by Auston** [fetus-hina/stat.ink#368]
Is possible add a icon column show weapons at battle list page, like 'Team'

**Comment by fetus-hina** [comment]
Unfortunately, it is difficult.
Stat.ink doesn't have weapons' icon.
If we use "official" weapons' icon, Nintendo may sues me. Because Japanese-Copyright-Law ("著作権法") hasn't fair-use clause(s).
I would like to remove the image of stages if possible.

By the way, at Splatoon 1, there were weapon images created by a user.
That icons still exist in our repository (https://github.com/fetus-hina/stat.ink/tree/master/resources/bukiicons) but we can't use it because weapon lineup is bit different between Splatoon 1 and 2.
If someone creates new icons (have open license or special permit to me), I will use it.

**Comment by Auston** [comment]
need icons at  /spl2/stat/by-weapon
