### ISSUE TITLE
missing document doc/api-2/struct/battle.md

### ISSUE THREAD

**Issue by ghost** [fetus-hina/stat.ink#430]
It has been referenced in https://github.com/fetus-hina/stat.ink/blob/5d17933ebf40e660a43c56cf5b751c787c24bb12/doc/api-2/get-battle.md

**Comment by fetus-hina** [comment]
Thank you report this issue.

The document won't be updated for a while because I'm busy and tired to update the doc.
Please refer the doc for `POST` API, real response and [the code](https://github.com/fetus-hina/stat.ink/blob/5d17933ebf40e660a43c56cf5b751c787c24bb12/models/Battle2.php#L1165).
Sorry for inconvenience.

P.S. You can create the doc and it's very welcome :)
